bookman_project/book/urls.py
from django.urls import path

from . import views

app_name = "book"
urlpatterns = [
    path("", views.index, name="index"),
    path("details/", views.details, name="details"),
    path("new-author", views.author_creation, name="author_creation"),
    path("new-publisher", views.publisher_creation, name="publisher_creation"),
    path("new-genre", views.genre_creation, name="genre_creation"),
    path("new-book", views.book_creation, name="book_creation"),
    path("my-books", views.user_books_view, name="user_books_view"),
    path('rent_book/', views.rent_book, name='rent_book'),
    path('recognition/', views.recognition, name='recognition'),
    path('manage/<int:book_id>/', views.manage_books, name='manage'),
    path('return_book/', views.return_book, name='return_book'),
    path('edit_book/<int:book_id>/', views.edit, name='edit'),
    path('delete_book/', views.delete, name='delete'),
]

bookman_project/bookman/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('book.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bookman_project/user/urls.py
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("list", views.list, name="list"),
    path("details", views.details, name="details"),
    path("creation", views.user_creation, name="user_creation")
]

bookman_project/book/models.py
import cv2
from django.db import models
from .orb_recognition import extract_descriptors
from pickle import dumps, loads
from PIL import Image
from .nn_embeds import get_embedding


def front_cover_upload_to(instance, filename):
    return f"book/{instance.id}/front_cover.jpg"


def back_cover_upload_to(instance, filename):
    return f"book/{instance.id}/back_cover.jpg"


class Author(models.Model):

    first_name = models.CharField(
        verbose_name="First name",
        max_length=20,
        null=True,
        blank=True
    )

    last_name = models.CharField(
        verbose_name="Last name",
        max_length=20,
        null=True,
        blank=True
    )

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Publisher(models.Model):

    name = models.CharField(
        verbose_name="Name",
        max_length=50,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name


class Genre(models.Model):

    name = models.CharField(
        verbose_name="Name",
        max_length=50,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name


class Book(models.Model):

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.is_available = self.user_set.count() < self.copies_available
        if self.front_cover:
            self.create_descriptors()
        if self.front_cover:
            self.genereate_embeddings()
        super().save(*args, **kwargs)

    def create_descriptors(self):
        front_cover = cv2.imread(self.front_cover.path)
        back_cover = cv2.imread(self.back_cover.path)
        self.descriptor_front = dumps(
            extract_descriptors(front_cover))
        self.descriptor_back = dumps(
            extract_descriptors(back_cover))

    title = models.CharField(
        verbose_name="Book title",
        max_length=50,
        null=True,
        blank=True
    )

    author = models.ForeignKey(
        Author,
        verbose_name="Author",
        on_delete=models.CASCADE
    )

    publisher = models.ForeignKey(
        Publisher,
        verbose_name="Publisher",
        on_delete=models.CASCADE
    )

    genre = models.ForeignKey(
        Genre,
        verbose_name="Genre",
        on_delete=models.CASCADE
    )

    front_cover = models.ImageField(
        verbose_name="Front cover",
        upload_to=front_cover_upload_to,
        null=True,
        blank=True
    )

    back_cover = models.ImageField(
        verbose_name="Back cover",
        upload_to=back_cover_upload_to,
        null=True,
        blank=True
    )

    copies_available = models.IntegerField(default=1)
    is_available = models.BooleanField(default=True)
    descriptor_front = models.BinaryField(null=True, blank=True)
    descriptor_back = models.BinaryField(null=True, blank=True)
    embed_front = models.BinaryField(null=True, blank=True)
    embed_back = models.BinaryField(null=True, blank=True)
    position = models.CharField(max_length=10, null=True, blank=True)

    def genereate_embeddings(self):
        front_cover = Image.open(self.front_cover.path)
        back_cover = Image.open(self.back_cover.path)
        self.embed_front = dumps(get_embedding(front_cover))
        self.embed_back = dumps(get_embedding(back_cover))

    def check_availability(self):
        self.is_available = self.user_set.count() < self.copies_available
        self.save()

    def __str__(self):
        return self.title

bookman_project/book/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from user.models import User
from .models import Book
from .orb_recognition import extract_descriptors, compare_descriptors
from django.contrib import messages

from . import models, forms
import pickle
import cv2
import numpy as np
from PIL import Image
from io import BytesIO
from .nn_embeds import get_embedding, compare_embeddings


def user_is_librarian(function):
    def wrapper(request, *args, **kwargs):
        if request.user.is_librarian:
            return function(request, *args, **kwargs)
        else:
            return redirect('/')
    return wrapper


def index(request):
    search_txt = request.GET.get('search', False)
    form = forms.BookSearchForm(request, request.GET)
    if form.is_valid():
        results = models.Book.objects.filter(
            title__contains=form.cleaned_data['search_txt'])
    return render(request, 'book/index.html', {'form': form, 'results': results})


def details(request):
    book_id = request.GET.get('id', False)
    if book_id:
        try:
            book = models.Book.objects.get(pk=book_id)
        except:
            book = None
        if book is not None:
            position = book.position.split(',')
            return render(request, 'book/details.html', {'book': book, 'position': position})
    else:
        return redirect('/')


@login_required
@user_is_librarian
def author_creation(request):
    form = forms.AuthorCreationForm()
    if request.method == "POST":
        form = forms.AuthorCreationForm(request.POST)
        if form.is_valid():
            author = models.Author(
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name']
            )
            author.save()
            return redirect('/')
    return render(request, 'book/author/creation.html', {'form': form})


@login_required
@user_is_librarian
def publisher_creation(request):
    form = forms.PublisherCreationForm()
    if request.method == "POST":
        form = forms.PublisherCreationForm(request.POST)
        if form.is_valid():
            publisher = models.Publisher(name=form.cleaned_data['name'])
            publisher.save()
            return redirect('/')
    return render(request, 'book/publisher/creation.html', {'form': form})


@login_required
@user_is_librarian
def genre_creation(request):
    form = forms.GenreCreationForm()
    if request.method == "POST":
        form = forms.GenreCreationForm(request.POST)
        if form.is_valid():
            genre = models.Genre(name=form.cleaned_data['name'])
            genre.save()
            return redirect('/')
    return render(request, 'book/genre/creation.html', {'form': form})


@login_required
@user_is_librarian
def book_creation(request):
    form = forms.BookCreationForm()
    if request.method == "POST":
        form = forms.BookCreationForm(request.POST, request.FILES)
        if form.is_valid():
            book = models.Book(
                title=form.cleaned_data['title'],
                author=form.cleaned_data['author'],
                publisher=form.cleaned_data['publisher'],
                genre=form.cleaned_data['genre'],
                copies_available=form.cleaned_data['copies_available'],
                position=form.cleaned_data['position'],
                front_cover=None,
                back_cover=None
            )
            book.save()
            book.front_cover = form.cleaned_data['front_cover']
            book.back_cover = form.cleaned_data['back_cover']
            book.save()
            book.check_availability()
            return redirect('/')
    return render(request, 'book/creation.html', {'form': form})


@login_required
def user_books_view(request):
    books = request.user.books.all()
    return render(request, 'book/user_books_view.html', {'books': books})


@login_required
@user_is_librarian
def rent_book(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        book_id = request.POST.get('book_id')
        user = User.objects.get(id=user_id)
        book = Book.objects.get(id=book_id)
        user.books.add(book)
        book.check_availability()
        return redirect('/')
    else:
        book_id = request.GET.get('book_id')
        book = Book.objects.get(id=book_id)
        book.check_availability()
        users = User.objects.all()
        parsed_position = book.position.split(',')
        return render(request, 'book/rent_book.html', {'book': book, 'users': users, 'parsed_position': parsed_position})


@login_required
@user_is_librarian
def return_book(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        book_id = request.POST.get('book_id')
        user = User.objects.get(id=user_id)
        book = Book.objects.get(id=book_id)
        user.books.remove(book)
        book.check_availability()
        return redirect('/')
    else:
        book_id = request.GET.get('book_id')
        book = Book.objects.get(id=book_id)
        book.check_availability()
        users = User.objects.filter(books=book)
        parsed_position = book.position.split(',')
        return render(request, 'book/return_book.html', {'book': book, 'users': users, 'parsed_position': parsed_position})


@login_required
@user_is_librarian
def recognition(request):
    if request.method == 'POST':

        # Get the uploaded image from the request
        uploaded_image = request.FILES.get('image')

        # Read the uploaded image using cv2
        image = cv2.imdecode(np.frombuffer(
            uploaded_image.read(), np.uint8), cv2.IMREAD_COLOR)

        # PIL image for neural network
        pil_image = Image.open(uploaded_image)

        # Process the uploaded image to extract descriptors
        descriptors = extract_descriptors(image)

        # Get the embeddings for the uploaded image
        embedding = get_embedding(pil_image)

        books = Book.objects.all()
        matches = []
        for book in books:
            # Load the pickled descriptors for front cover and back cover
            front_cover_descriptors = pickle.loads(
                book.descriptor_front)
            back_cover_descriptors = pickle.loads(book.descriptor_back)

            # Compare descriptors with both the front cover and back cover

            front_cover_score = compare_descriptors(
                descriptors, front_cover_descriptors)
            back_cover_score = compare_descriptors(
                descriptors, back_cover_descriptors)

            # Load the pickled embeddings for front cover and back cover

            front_cover_embedding = pickle.loads(book.embed_front)
            back_cover_embedding = pickle.loads(book.embed_back)

            # Compare embeddings with both the front cover and back cover

            front_cover_nn_score = compare_embeddings(
                embedding, front_cover_embedding)
            back_cover_nn_score = compare_embeddings(
                embedding, back_cover_embedding)

            # Load embeddings for front cover and back cover

            front_cover_embedding = pickle.loads(book.embed_front)
            back_cover_embedding = pickle.loads(book.embed_back)

            # Store the book and its best score in the matches list

            best_score = max(front_cover_score, back_cover_score)
            best_nn_score = round(
                max(front_cover_nn_score, back_cover_nn_score) * 100, 2)
            matches.append((book.id, best_score, best_nn_score))

        # Sort the matches by score in descending order and take the top 5

        matches = [(Book.objects.get(id=match_id), orb_score, nn_score)
                   for match_id, orb_score, nn_score in matches]
        top_matches = sorted(matches, key=lambda x: x[1], reverse=True)[:5]
        return render(request, 'book/search_result.html', {'matches': top_matches})
    else:
        return render(request, 'book/recognition.html')


@login_required
@user_is_librarian
def edit(request, book_id):
    book = models.Book.objects.get(id=book_id)
    form = forms.BookEditForm(request.POST or None,
                              request.FILES or None, instance=book)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('/')

    return render(request, 'book/edit.html', {'form': form, 'book': book})


def delete(request):
    book_id = request.GET.get('book_id')
    if request.method == 'POST':
        book = models.Book.objects.get(id=book_id)
        book.delete()
        return redirect('/')
    else:
        book = models.Book.objects.get(id=book_id)
        return render(request, 'book/delete.html', {'book': book})


@login_required
@user_is_librarian
def manage_books(request, book_id):
    book = Book.objects.get(id=book_id)
    return render(request, 'book/manage.html', {'book': book})

bookman_project/book/templates/book/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta name="description" content="Book managing app">
        <meta name="keywords" content="book, bookman, library">
        <title>Book Manager
            {% block tab_title %}
            {% endblock tab_title %}
        </title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
              rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.min.css"
              rel="stylesheet" />
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
              integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
              crossorigin="anonymous"
              referrerpolicy="no-referrer" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top"
             style="margin-bottom: 20px">
            <div class="container-fluid">
                <a class="navbar-brand me-2" href="{% url "book:index" %}">
                    <img src="{% static 'book/img/bookman.png' %}"
                         height="30"
                         width="30"
                         alt="bookman logo" />
                </a>
                <a class="navbar-brand me-2">
                    {% block title %}
                    {% endblock title %}
                </a>
                <button data-mdb-collapse-init
                        class="navbar-toggler"
                        type="button"
                        data-mdb-target="#bookmanNavbar"
                        aria-controls="bookmanNavbar"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="bookmanNavbar">
                    {% if user.is_authenticated %}
                        {% if user.books.all %}
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'book:user_books_view' %}">My Books</a>
                                </li>
                            </ul>
                        {% endif %}
                        {% if user.is_librarian %}
                            <!-- Left Links -->
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item dropdown">
                                    <a data-mdb-dropdown-init
                                       class="nav-link dropdown-toggle"
                                       href="#"
                                       id="bookmanCreateDropdown"
                                       role="button"
                                       aria-expanded="false">Create</a>
                                    <ul class="dropdown-menu" aria-labelledby="bookmanCreateDropdown">
                                        <li>
                                            <a class="dropdown-item" href="{% url 'book:book_creation' %}">Book</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="{% url 'book:genre_creation' %}">Genre</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="{% url 'book:publisher_creation' %}">Publisher</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="{% url 'book:author_creation' %}">Author</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'user:list' %}">Users</a>
                                </li>
                            </ul>
                            <!-- End of Left links -->
                        {% endif %}
                        <div class="d-flex align-items-center" style="margin-left: auto;">
                            <span class="navbar-text">Logged in as {{ user.username }}</span>
                            <button data-mdb-ripple-init
                                    type="button"
                                    class="btn btn-primary me-3"
                                    style="margin-left: 20px">
                                <a class="text-white" href="{% url 'user:logout' %}">Logout</a>
                            </button>
                        </div>
                    {% else %}
                        <div class="d-flex align-items-center" style="margin-left: auto;">
                            <a class="btn btn-primary btn-rounded me-2"
                               href="{% url 'user:login' %}">Login</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </nav>
        {% block body_content %}
        {% endblock body_content %}
        <script type="text/javascript"
                src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.umd.min.js"></script>
    </body>
</html>

bookman_project/book/templates/book/creation.html
{% extends "book/form.html" %}
{% load static %}
{% block tab_title %}- Book Creation{% endblock tab_title %}
{% block title %}
    Create a book
{% endblock title %}
{% block form_heading %}
    Register a book
{% endblock form_heading %}
{% block form_content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
{% endblock form_content %}

bookman_project/book/templates/book/delete.html
{% extends "book/base.html" %}
{% block tab_title %}
    - Delete Book
{% endblock tab_title %}
{% block title %}
    Delete book {{ book.title }}
{% endblock title %}
{% block body_content %}
    <div class="d-flex flex-column align-items-center justify-content-center">
        <h1 class="text-danger">Are you sure you want to delete book {{ book.title }}?</h1>
        <form action="" method="post">
            <input type="hidden" name="token" value="{{ book.id }}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
            <a href="{% url "book:index" %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock body_content %}

bookman_project/book/templates/book/details.html
{% extends "book/base.html" %}
{% block tab_title %}
    - {{ book.title }}
{% endblock tab_title %}
{% block title %}
    Details for: {{ book.title }} by {{ book.author }}
{% endblock title %}
{% load static %}
{% block body_content %}
    <div class="d-flex flex-column align-items-center justify-content-center"
         style="height: 100vh">
        {% if book in user.books.all %}
            <div class="alert alert-warning" role="alert">You already have this book in your <a href="{% url "book:user_books_view" %}">library</a>.</div>
        {% endif %}
        {% if book.is_available %}
        {% else %}
            <div class="alert alert-danger" role="alert">This book is currently unavailable.</div>
        {% endif %}
        <div class="book text-center">
            <img class="mb-3"
                 src="{{ book.front_cover.url }}"
                 style="width: 300px;
                        height: 400px;
                        object-fit: cover"
                 alt="front cover">
            <h1 class="mb-3">{{ book.title }}</h1>
            <p class="mb-1">
                <strong>Author:</strong> {{ book.author }}
            </p>
            <p class="mb-1">
                <strong>Publisher:</strong> {{ book.publisher }}
            </p>
            <p class="mb-1">
                <strong>Genre:</strong> {{ book.genre }}
            </p>
            {% if user.is_librarian %}
            <p class="mb-1">
                <strong>Position:</strong> Shelf: {{ position.0 }}; Section: {{ position.1 }}; Cell: {{ position.2 }} 
            </p>
            {% endif %}
        </div>
        {% if user.is_librarian %}
            {% if book.is_available %}
                <form method="get" action="{% url 'book:rent_book' %}">
                    <input type="hidden" name="book_id" value="{{ book.id }}">
                    <button type="submit" class="btn btn-primary mb-1">Rent-out</button>
                </form>
            {% else %}
                <button type="submit" class="btn btn-primary mb-1" disabled>Rent-out</button>
            {% endif %}
            <form method="get" action="{% url 'book:edit' book.id %}">
                <button type="submit" class="btn btn-warning mb-1">Edit</button>
            </form>
            <form method="get" action="{% url 'book:delete' %}">
                <input type="hidden" name="book_id" value="{{ book.id }}">
                <button type="submit" class="btn btn-danger mb-1">Delete</button>
            </form>
        {% endif %}
    </div>
{% endblock body_content %}

bookman_project/book/templates/book/edit.html
{% extends "book/form.html" %}
{% block tab_title %}- Edit Book{% endblock tab_title %}
{% block form_heading %}Edit book{% endblock form_heading %}
{% block form_content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
{% endblock form_content %}

bookman_project/book/templates/book/index.html
{% extends "book/base.html" %}
{% load static %}
{% block title %}
    Bookman
{% endblock title %}
{% block body_content %}
    <div class="container" style="width: fit-content; margin-bottom: 15px;">
        <form action=""
              method="get"
              class="d-flex"
              role="search"
              style="margin-left: 5px">
            {% csrf_token %}
            {{ form.search_txt }}
            <input type="submit"
                   value="Search"
                   class="btn btn-outline-success"
                   style="margin-left: 10px">
        </form>
    </div>
    <div class="row g-4 m-0">
        {% for book in results %}
            <div class="col d-flex justify-content-center">
                <div class="card text-center shadow-4-strong"
                     style="width: 18rem;
                            height: 25rem">
                    <div class="bg-image hover-overlay"
                         data-mdb-ripple-init
                         data-mdb-ripple-color="light">
                        <img src="{{ book.front_cover.url }}" class="img-fluid" alt="front cover" />
                        <a href="{% url 'book:details' %}?id={{ book.id }}">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ book.title }}</h5>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% if user.is_librarian %}
        <button class="btn btn-floating btn-primary btn-lg"
                style="position: fixed;
                       bottom: 20px;
                       right: 20px;
                       z-index: 100">
            <a href="{% url "book:recognition" %}">
                <i class="fas fa-camera fa-2x text-white"></i>
            </a>
        </button>
    {% endif %}
{% endblock body_content %}

bookman_project/book/templates/book/manage.html
{% extends "book/base.html" %}
{% block tab_title %}
    - Manage Book
{% endblock tab_title %}
{% block title %}
    Manage "{{ book.title }}"
{% endblock title %}
{% block body_content %}
    <div class="d-flex flex-column align-items-center justify-content-center"
         style="height: 100vh">
        <div class="book text-center">
            <img class="mb-3"
                 src="{{ book.front_cover.url }}"
                 style="width: 300px;
                        height: 400px;
                        object-fit: cover"
                 alt="front cover">
            <h1 class="mb-3">{{ book.title }}</h1>
            <p class="mb-1">
                <strong>Author:</strong> {{ book.author }}
            </p>
            <p class="mb-1">
                <strong>Publisher:</strong> {{ book.publisher }}
            </p>
            <p class="mb-1">
                <strong>Genre:</strong> {{ book.genre }}
            </p>
        </div>
        <div class="d-flex justify-content-center">
            {% if book.is_available %}
                <form class="me-4" method="get" action="{% url 'book:rent_book' %}">
                    <input type="hidden" name="book_id" value="{{ book.id }}">
                    <button type="submit" class="btn btn-primary mr-2">Rent-out</button>
                </form>
            {% else %}
                <button type="submit" class="btn btn-primary me-4" disabled>Rent-out</button>
            {% endif %}
            <form method="get" action="{% url 'book:return_book' %}">
                <input type="hidden" name="book_id" value="{{ book.id }}">
                <button type="submit" class="btn btn-warning">Return</button>
            </form>
        </div>
    </div>
{% endblock body_content %}

bookman_project/book/templates/book/search_result.html
{% extends "book/base.html" %}
{% block tab_title %}
    - Results for image search
{% endblock tab_title %}
{% block title %}
    Results for image search
{% endblock title %}
{% block body_content %}
    <div class="row g-4 m-0">
        {% for match in matches %}
            <div class="col d-flex justify-content-center">
                <div class="card text-center shadow-4-strong"
                     style="width: 18rem;
                            height: 25rem">
                    <div class="bg-image hover-overlay"
                         data-mdb-ripple-init
                         data-mdb-ripple-color="light">
                        <img src="{{ match.0.front_cover.url }}"
                             class="img-fluid"
                             alt="front cover" />
                        <a href="{% url 'book:manage' match.0.id %}">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Score: {{ match.1 }}</h5>
                        <h5 class="card-title">Neural Network Score: {{ match.2 }}</h5>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock body_content %}
<img src="{{ match.0.front_cover.url }}" alt="Book cover">
<p>Score: {{ match.1 }}</p>

bookman_project/book/templates/book/user_books_view.html
{% extends "book/base.html" %}
{% block title %}
    My Library
{% endblock title %}
{% block body_content %}
    {% if books %}
        <div class="row g-4 m-0">
            {% for book in books %}
                <div class="col d-flex justify-content-center">
                    <div class="card text-center shadow-4-strong"
                         style="width: 18rem;
                                height: 25rem">
                        <div class="bg-image hover-overlay"
                             data-mdb-ripple-init
                             data-mdb-ripple-color="light">
                            <img src="{{ book.front_cover.url }}" class="img-fluid" alt="front cover" />
                            <a href="{% url 'book:details' %}?id={{ book.id }}">
                                <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                            </a>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ book.title }}</h5>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div>
            <h1 class="text-center">No books in your Library</h1>
        </div>
    {% endif %}
{% endblock body_content %}