bookman_project/book/urls.py
from django.urls import path

from . import views

app_name = "book"
urlpatterns = [
    path("", views.index, name="index"),
    path("details/", views.details, name="details"),
    path("new-author", views.author_creation, name="author_creation"),
    path("new-publisher", views.publisher_creation, name="publisher_creation"),
    path("new-genre", views.genre_creation, name="genre_creation"),
    path("new-book", views.book_creation, name="book_creation"),
    path("my-books", views.user_books_view, name="user_books_view"),
    path('rent_book/', views.rent_book, name='rent_book'),
    path('recognition/', views.recognition, name='recognition'),
    path('manage/<int:book_id>/', views.manage_books, name='manage'),
    path('return_book/', views.return_book, name='return_book'),
    path('edit_book/<int:book_id>/', views.edit, name='edit'),
    path('delete_book/', views.delete, name='delete'),
]

bookman_project/bookman/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('book.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bookman_project/user/urls.py
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("list", views.list, name="list"),
    path("details", views.details, name="details"),
    path("creation", views.user_creation, name="user_creation")
]

bookman_project/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from book.models import Book


class User(AbstractUser):

    is_librarian = models.BooleanField(default=False)
    books = models.ManyToManyField(Book, blank=True)

    def __str__(self):
        return self.username

bookman_project/user/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.core.validators import EmailValidator

from . import models


class LoginForm(forms.Form):

    username = forms.CharField(
        label="Username",
        max_length=50
    )

    password = forms.CharField(
        label="Password",
        max_length=50,
        widget=forms.PasswordInput()
    )


class UserCreationForm(forms.Form):
    username = forms.CharField(
        label="Username",
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password1 = forms.CharField(
        label="Password",
        max_length=50,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        label="Confirm password",
        max_length=50,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )

    def as_p(self):
        "Returns this form rendered as HTML <p>s."
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(label)s %(field)s%(help_text)s</p>',
            error_row='<div class="alert alert-danger" role="alert">%s</div>',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=False)

    def clean(self):
        username = self.cleaned_data['username']
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        email = self.cleaned_data.get('email')

        error_messages = []
        validator = EmailValidator()
        try:
            validator(email)
        except ValidationError:
            error_messages.append(_("Invalid email address."))

        for user in models.User.objects.all():
            if user.username == username:
                error_messages.append(_("Username %(username)s already used.") % {
                                      "username": username})
            elif user.email == email:
                error_messages.append(
                    _("Email %(email)s already used.") % {"email": email})
        if password1 != password2:
            error_messages.append(_("Entered password differ."))

        if error_messages:
            raise ValidationError(error_messages)

        return self.cleaned_data


class UserSearchForm(forms.Form):
    search_txt = forms.CharField(
        label="Search text",
        max_length=50,
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control rounded', type: 'search', 'placeholder': 'Search Users', })
    )

    def __init__(self, request, *args, **kwargs):
        super(UserSearchForm, self).__init__(*args, **kwargs)
        self.fields['search_txt'].initial = request.GET.get('search', '')

bookman_project/user/views.py
from django.contrib import admin as django_admin
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout, login
from django.db.models import Q

from . import forms, models, admin


def login_view(request):
    form = forms.LoginForm()
    if request.method == "POST":
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password']
            )
            if user is not None:
                login(request, user)
                return redirect('/')
    return render(request, 'user/login.html', {'form': form})


@login_required
def logout_view(request):
    logout(request)
    return redirect('/')


def user_creation(request):
    form = forms.UserCreationForm()
    if request.method == "POST":
        form = forms.UserCreationForm(request.POST)
        if form.is_valid():
            user = models.User.objects.create_user(
                form.cleaned_data['username'],
                form.cleaned_data['email'],
                form.cleaned_data['password1']
            )
            user.save()
            return redirect('/')
    return render(request, 'user/creation.html', {'form': form})


@login_required
def details(request):
    username = request.GET.get('user', False)
    if username:
        try:
            user = models.User.objects.get(username=username)
        except:
            user = None
        if user is not None and admin.UserAdmin(models.User, django_admin.site).has_view_permission(request, user):
            if request.method == 'POST':
                book_id = request.POST.get('book_id')
                book = models.Book.objects.get(id=book_id)
                user.books.remove(book)
                book.check_availability()
            books = user.books.all()
            return render(request, 'user/detail.html', {'page_user': user, 'books': books})
        else:
            return redirect('/')
    else:
        return redirect('/')


@login_required
def list(request):
    if request.user.is_librarian:
        search_txt = request.GET.get('search', False)
        form = forms.UserSearchForm(request, request.GET)
        if form.is_valid():
            results = models.User.objects.filter(
                Q(username__contains=form.cleaned_data['search_txt']) |
                Q(email__contains=form.cleaned_data['search_txt'])
            )
        return render(request, 'user/list.html', {'form': form, 'results': results})
    else:
        return redirect('/')

bookman_project/user/templates/user/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta name="description" content="Book managing app">
        <meta name="keywords" content="book, bookman, library">
        <title>Book Manager
            {% block tab_title %}
            {% endblock tab_title %}
        </title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
              rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.min.css"
              rel="stylesheet" />
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
              integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
              crossorigin="anonymous"
              referrerpolicy="no-referrer" />
        {% block head_content %}
        {% endblock head_content %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top"
             style="margin-bottom: 20px">
            <div class="container-fluid">
                <a class="navbar-brand me-2">
                    {% block title %}
                    {% endblock title %}
                </a>
                <button data-mdb-collapse-init
                        class="navbar-toggler"
                        type="button"
                        data-mdb-target="#bookmanNavbar"
                        aria-controls="bookmanNavbar"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="bookmanNavbar">
                    <!-- Left Links -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'book:index' %}">Homepage</a>
                        </li>
                    </ul>
                    <!-- End of Left links -->
                    <div class="d-flex align-items-center" style="margin-left: auto;">
                        {% block navbar_content %}
                        {% endblock navbar_content %}
                    </div>
                </div>
            </div>
        </nav>
        {% block body_content %}
        {% endblock body_content %}
        <script type="text/javascript"
                src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.umd.min.js"></script>
    </body>
</html>

bookman_project/user/templates/user/creation.html
{% extends "user/form.html" %}
{% load static %}
{% block tab_title %}
    - User Creation
{% endblock tab_title %}
{% block title %}
    User Creation
{% endblock title %}
{% block form_heading %}
    User Creation
{% endblock form_heading %}
{% block form_content %}
    {% if user.is_authenticated %}
        <div class="alert alert-danger">
            <ul>
                <li>You are already logged in as {{ user.username }}.</li>
            </ul>
            <button data-mdb-ripple-init
                    type="button"
                    class="btn btn-primary btn-block"
                    onclick="window.location.href = '{% url 'book:index' %}'">Go back to Homepage</button>
        </div>
    {% else %}
        <form style="width: 300px" method="post">
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for error in form.non_field_errors %}<li>{{ error }}</li>{% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div data-mdb-input-init class="form-outline mb-4">
                <input type="text"
                       id="username"
                       class="form-control"
                       name="{{ form.username.name }}"
                       required />
                <label class="form-label" for="username">{{ form.username.label }}</label>
            </div>
            <div data-mdb-input-init class="form-outline mb-4">
                <input type="password"
                       id="password1"
                       class="form-control"
                       name="{{ form.password1.name }}"
                       required />
                <label class="form-label" for="password1">{{ form.password1.label }}</label>
            </div>
            <div data-mdb-input-init class="form-outline mb-4">
                <input type="password"
                       id="password2"
                       class="form-control"
                       name="{{ form.password2.name }}"
                       required />
                <label class="form-label" for="password2">{{ form.password2.label }}</label>
            </div>
            <div data-mdb-input-init class="form-outline mb-4">
                <input type="email"
                       id="email"
                       class="form-control"
                       name="{{ form.email.name }}"
                       required />
                <label class="form-label" for="email">{{ form.email.label }}</label>
            </div>
            <button data-mdb-ripple-init type="submit" class="btn btn-primary btn-block">Register Account</button>
        </form>
    {% endif %}
{% endblock form_content %}

bookman_project/user/templates/user/detail.html
{% extends "user/base.html" %}
{% block title %}
    Details for {{ page_user.username }}
{% endblock title %}
{% block body_content %}
    <div class="d-flex flex-column align-items-center justify-content-center"
         style="height: 100vh">
        <h2>{{ page_user.username }}</h2>
        <p>{{ page_user.email }}</p>
        <h3>Books:</h3>
        <div class="row g-4 m-0">
            {% for book in books %}
                <div class="col d-flex justify-content-center">
                    <div class="card text-center shadow-4-strong"
                         style="width: 18rem;
                                height: 25rem">
                        <div class="bg-image">
                            <img src="{{ book.front_cover.url }}" class="img-fluid" alt="front cover" />
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ book.title }}</h5>
                            <form method="post" action="">
                                {% csrf_token %}
                                <input type="hidden" name="book_id" value="{{ book.id }}">
                                <button type="submit" class="btn btn-warning" data-mdb-ripple-init>Return</button>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock body_content %}

bookman_project/user/templates/user/form.html
{% extends "user/base.html" %}
<!DOCTYPE html>
{% block tab_title %}
    - Login
{% endblock tab_title %}
{% block title %}
{% endblock title %}
{% block body_content %}
    <div class="d-flex flex-column align-items-center justify-content-center"
         style="height: 100vh">
        <h2>
            {% block form_heading %}
            {% endblock form_heading %}
        </h2>
        {% block form_content %}
        {% endblock form_content %}
    </div>
{% endblock body_content %}

bookman_project/user/templates/user/list.html
{% extends "user/base.html" %}
{% load static %}
{% block title %}
    Search Users
{% endblock title %}
{% block navbar_content %}
    <form class="d-flex input-group w-auto">
        {% csrf_token %}
        {{ form.search_txt }}
        <input class="btn btn-primary"
               style="margin-left: 10px"
               type="submit"
               value="Search">
    </form>
{% endblock navbar_content %}
{% block body_content %}
    <div class="container-sm d-flex justify-content-center align-items-center flex-column">
        {% for person in results %}
            <div class="card bg-light mb-3">
                <a class="person"
                   href="{% url 'user:details' %}?user={{ person.username }}">
                    <p class="card-body">{{ person.username }}</p>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock body_content %}

bookman_project/user/templates/user/login.html
{% extends "user/form.html" %}
{% block tab_title %}
    - Login
{% endblock tab_title %}
{% block title %}
    Login
{% endblock title %}
{% block form_heading %}
    Login
{% endblock form_heading %}
{% block form_content %}
    <form style="width: 300px" method="post">
        {% csrf_token %}
        <div data-mdb-input-init class="form-outline mb-4">
            <input type="text"
                   id="form1Example1"
                   class="form-control"
                   name="{{ form.username.name }}"
                   required />
            <label class="form-label" for="form1Example1">{{ form.username.label }}</label>
        </div>
        <!-- Password input -->
        <div data-mdb-input-init class="form-outline mb-4">
            <input type="password"
                   id="form1Example2"
                   class="form-control"
                   name="{{ form.password.name }}"
                   required />
            <label class="form-label" for="form1Example2">{{ form.password.label }}</label>
        </div>
        <!-- Register now link -->
        <p>
            Not a member?
            <a href="{% url 'user:user_creation' %}">Register</a>
        </p>
        <!-- Submit button -->
        <button data-mdb-ripple-init type="submit" class="btn btn-primary btn-block">Log In</button>
    </form>
{% endblock form_content %}